const integrations = [
  ['GitHub','Code','Repositories, stars, contributions','GH','github'],['GitLab','Code','Projects, merge requests, activity','GL','gitlab'],['Bitbucket','Code','Repositories, pull requests','BB','bitbucket'],['npm','Code','Packages, downloads, dependents','npm','npm'],['PyPI','Code','Packages, releases, projects','Py','pypi'],['Stack Overflow','Learning','Reputation, answers, badges','SO','stack'],['LeetCode','Learning','Solved problems, contests, rank','LC','leet'],['HackerRank','Learning','Skills, certificates, challenges','HR','hack'],['freeCodeCamp','Learning','Certifications, projects','FC','fcc'],['dev.to','Writing','Articles, reactions, followers','D','devto'],['Hashnode','Writing','Posts, followers, publications','H','hashnode'],['Medium','Writing','Stories, claps, publications','M','medium'],['LinkedIn','Social','Experience, skills, connections','in','linkedin'],['X','Social','Posts, followers, communities','𝕏','x'],['Reddit','Social','Posts, karma, communities','R','reddit'],['YouTube','Social','Videos, playlists, subscribers','▶','youtube'],['Figma','Design','Files, projects, prototypes','F','figma'],['Discord','Community','Servers, roles, activity','D','discord'],['Product Hunt','Community','Products, launches, followers','PH','product'],['Hugging Face','Data & AI','Models, datasets, spaces','HF','hugging']
];
const routeNames={home:'Overview',integrations:'Integrations',feed:'Community feed',discover:'Discover',profile:'My profile',imports:'Import history',settings:'Settings'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function renderIntegrations(query=''){$('#integration-grid').innerHTML=integrations.filter(x=>x[0].toLowerCase().includes(query.toLowerCase())).map((x,i)=>`<article class="integration-card"><div class="integration-top"><span class="source-logo ${x[4]}">${x[3]}</span><span class="status ${i<4?'connected':''}">${i<4?'Connected':'Not connected'}</span></div><h3>${x[0]}</h3><p>${x[2]}</p><small>${x[1]}</small><button class="${i<4?'secondary-button':'primary-button'} connect-button" data-source="${x[0]}">${i<4?'Manage':'Connect'} <span>→</span></button></article>`).join('');$$('.connect-button').forEach(b=>b.onclick=()=>openModal(b.dataset.source));}
function openModal(source='GitHub'){$('#import-modal').classList.add('open');$('#import-modal').setAttribute('aria-hidden','false');$('#modal-title').textContent=`Connect ${source}`;wizardStep=1;renderWizard();}
function closeModal(){$('#import-modal').classList.remove('open');$('#import-modal').setAttribute('aria-hidden','true');}
let wizardStep=1;
function renderWizard(){const c=$('#wizard-content');if(wizardStep===1)c.innerHTML=`<div class="oauth-card"><span class="source-logo github large-logo">GH</span><h3>Authorize read-only access</h3><p>DevBridge will never modify your account.</p><ul><li>✓ View your public repositories</li><li>✓ Read your contribution graph</li><li>✓ View your followers and following</li></ul><small>ⓘ You can revoke access anytime from account settings.</small></div>`;if(wizardStep===2)c.innerHTML=`<div class="wizard-options"><h3>What should we import?</h3><p class="muted">Choose the data that makes your profile complete.</p>${['Repositories','Contribution graph','Pull requests','Followers & following','Gists'].map((x,i)=>`<label><input type="checkbox" checked> <span><b>${x}</b><small>${['Projects you have built and contributed to','Your activity over the last year','Your open source collaboration','Your developer network','Your public code snippets'][i]}</small></span></label>`).join('')}</div>`;if(wizardStep===3)c.innerHTML=`<div class="wizard-options"><h3>Choose your privacy defaults</h3><p class="muted">You can change these per item later.</p>${['Repositories','Contribution graph','Followers & following'].map(x=>`<div class="privacy-row"><b>${x}</b><select><option>Public</option><option>Community only</option><option>Private</option></select></div>`).join('')}<div class="notice compact">✓ You control your data. Revoke access anytime.</div></div>`;if(wizardStep===4)c.innerHTML=`<div class="import-success"><div class="success-mark">✓</div><h3>Import complete</h3><p>1,052 items are now part of your DevBridge profile.</p><div class="import-counts"><span><b>842</b> repos</span><span><b>186</b> contributions</span><span><b>24</b> followers</span></div></div>`;$('#wizard-next').innerHTML=wizardStep===4?'View my profile <span>→</span>':'Continue <span>→</span>';$$('.stepper span').forEach((s,i)=>s.classList.toggle('current',i===wizardStep-1));}
function renderFeed(){$('#feed-list').innerHTML=[['Maria Rodriguez','published a new article','Building reliable queues with Rust','Hashnode','MR','avatar-coral'],['Sam Kim','shipped v2.1 of','react-forms','npm','SK','avatar-green'],['Jordan Taylor','solved 50 problems this month','Dynamic programming patterns','LeetCode','JT','avatar-blue']].map(x=>`<article class="feed-card"><div class="feed-author"><span class="avatar ${x[5]}">${x[4]}</span><div><b>${x[0]}</b><span>${x[1]}</span><small>2 hours ago · ${x[3]}</small></div><button>•••</button></div><h3>${x[2]}</h3><p>Sharing a small update with the community. What are you learning or building this week?</p><div class="feed-actions"><button>♡ 24</button><button>◌ 8 comments</button><button>⌑ Save</button></div></article>`).join('');}
function renderHeatmap(){let h='';for(let i=0;i<84;i++)h+=`<i class="heat-${Math.floor(Math.random()*5)}"></i>`;$('#heatmap').innerHTML=h;}
function route(){let id=location.hash.slice(1)||'home';if(!routeNames[id])id='home';$$('.route-section').forEach(s=>s.classList.toggle('active',s.id===id));$$('.nav-item').forEach(a=>a.classList.toggle('active',a.dataset.route===id));$('#page-title').textContent=routeNames[id];window.scrollTo(0,0);}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
renderIntegrations();renderFeed();renderHeatmap();route();window.addEventListener('hashchange',route);$('#integration-search').oninput=e=>renderIntegrations(e.target.value);$('#hero-connect').onclick=()=>openModal();$('#hero-connect-2').onclick=()=>openModal();$('#modal-close').onclick=closeModal;$('#modal-cancel').onclick=closeModal;$('#import-now').onclick=()=>openModal();$('#import-modal').onclick=e=>{if(e.target.id==='import-modal')closeModal()};$('#wizard-next').onclick=()=>{if(wizardStep<4){wizardStep++;renderWizard();if(wizardStep===4)toast('Your data was imported successfully.')}else{closeModal();location.hash='profile'}};$('#theme-toggle').onclick=()=>{document.body.classList.toggle('light-theme');toast(document.body.classList.contains('light-theme')?'Light mode enabled':'Dark mode enabled')};$('#command-button').onclick=()=>{const q=prompt('Search DevBridge');if(q)toast(`Searching for “${q}”`)};$('#mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open');
