import Link from 'next/link'
import { notFound } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { DeveloperCard, type Developer } from '@/components/discovery/developer-card'

export default async function ProfilePage({ params }: { params: Promise<{ username: string }> }) {
  const { username } = await params
  const supabase = await createClient()
  const [{ data: profile }, { data: { user } }] = await Promise.all([supabase.from('profiles').select('id,display_name,username,bio,avatar_url,website,github,interests').ilike('username', username).maybeSingle(), supabase.auth.getUser()])
  if (!profile?.username) notFound()
  const [{ count: followers }, { count: following }, { data: relationship }] = await Promise.all([supabase.from('follows').select('*', { count: 'exact', head: true }).eq('following_id', profile.id), supabase.from('follows').select('*', { count: 'exact', head: true }).eq('follower_id', profile.id), user ? supabase.from('follows').select('following_id').eq('follower_id', user.id).eq('following_id', profile.id).maybeSingle() : Promise.resolve({ data: null })])
  const developer: Developer = { ...profile, username: profile.username, interests: profile.interests ?? [], follower_count: followers ?? 0, following: Boolean(relationship) }
  const isOwner = user?.id === profile.id
  return <main className="min-h-screen bg-background"><div className="mx-auto max-w-4xl px-4 py-8 sm:px-6"><div className="flex items-center justify-between"><Link href="/discover" className="font-mono text-lg font-bold">commun<span className="text-accent">.</span></Link><Link href="/discover" className="text-sm text-muted hover:text-foreground">Discover developers</Link></div><section className="mt-14 rounded-2xl border border-border bg-surface p-6 sm:p-10"><div className="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-center gap-4"><span className="grid size-20 place-items-center rounded-full bg-accent/15 text-3xl font-semibold text-accent">{profile.display_name.slice(0, 1).toUpperCase()}</span><div><h1 className="text-3xl font-semibold tracking-tight">{profile.display_name}</h1><p className="mt-1 font-mono text-sm text-muted">@{profile.username}</p></div></div>{isOwner ? <Link href="/settings" className="rounded-lg border border-border px-4 py-2 text-sm font-medium hover:border-accent">Edit profile</Link> : <DeveloperCard developer={developer} authenticated={Boolean(user)} />}</div><p className="mt-8 max-w-2xl text-base leading-7 text-muted">{profile.bio || 'No bio added yet.'}</p><div className="mt-6 flex flex-wrap gap-2">{developer.interests.map((interest) => <span key={interest} className="rounded-md border border-border px-2.5 py-1.5 font-mono text-xs text-muted">{interest}</span>)}</div><div className="mt-8 flex flex-wrap gap-6 border-t border-border pt-6 font-mono text-sm text-muted"><span><strong className="text-foreground">{followers ?? 0}</strong> followers</span><span><strong className="text-foreground">{following ?? 0}</strong> following</span>{profile.website && <a href={profile.website} rel="noreferrer" target="_blank" className="text-accent hover:underline">Website</a>}{profile.github && <a href={profile.github} rel="noreferrer" target="_blank" className="text-accent hover:underline">GitHub</a>}</div></section><section className="mt-10"><div className="flex gap-6 border-b border-border" role="tablist"><span className="border-b-2 border-accent pb-3 text-sm font-semibold">Overview</span><span className="pb-3 text-sm text-muted">Articles</span><span className="pb-3 text-sm text-muted">Discussions</span><span className="pb-3 text-sm text-muted">Activity</span></div><div className="mt-6 rounded-xl border border-dashed border-border p-8 text-center"><p className="font-mono text-xs uppercase tracking-[0.16em] text-accent">Overview</p><p className="mt-3 text-sm text-muted">No published articles or discussions yet.</p></div></section></div></main>
}
