import Link from 'next/link'

const capabilities = [
  ['01', 'Discover', 'Find useful developers, technical articles, topics, and discussions.', '⌕'],
  ['02', 'Publish', 'Turn what you are learning into knowledge someone else can use.', '↗'],
  ['03', 'Discuss', 'Ask better questions and participate in conversations with context.', '↔'],
  ['04', 'Follow', 'Keep up with the people and topics that move your work forward.', '+'],
  ['05', 'Save', 'Keep the best ideas close for the next time you need them.', '▱'],
  ['06', 'Build your identity', 'Create a public developer profile around your knowledge and work.', '◎'],
]

function ProductPreview() {
  return <div className="relative mx-auto w-full max-w-[540px]" aria-label="Illustrated Commun product preview">
    <div className="absolute -inset-8 rounded-full bg-accent/10 blur-3xl" />
    <div className="relative overflow-hidden rounded-2xl border border-border bg-surface shadow-2xl shadow-black/30">
      <div className="flex items-center justify-between border-b border-border px-5 py-4"><span className="font-mono text-[10px] uppercase tracking-[0.24em] text-muted">Commun / explore</span><span className="flex items-center gap-2 font-mono text-[10px] text-muted"><i className="size-1.5 rounded-full bg-emerald-400" /> live space</span></div>
      <div className="grid gap-4 p-5 sm:grid-cols-[1.05fr_.95fr]">
        <div className="rounded-xl border border-border bg-background p-5"><div className="mb-8 flex items-center justify-between"><span className="font-mono text-[10px] text-accent">FEATURED NOTE</span><span className="text-xs text-muted">8 min read</span></div><h3 className="max-w-xs text-xl font-semibold leading-tight tracking-tight">The details that make a system feel calm.</h3><p className="mt-4 text-sm leading-6 text-muted">A place for considered technical writing, practical lessons, and work in progress.</p><div className="mt-10 flex items-center gap-3"><div className="flex size-8 items-center justify-center rounded-full border border-accent/40 bg-accent/10 font-mono text-xs text-accent">AK</div><div><p className="text-xs font-medium">A. Kumar</p><p className="font-mono text-[10px] text-muted">systems · design</p></div></div></div>
        <div className="flex flex-col gap-4"><div className="rounded-xl border border-border bg-background p-4"><div className="flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-widest text-muted">People to follow</span><span className="text-accent">→</span></div><div className="mt-5 flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-full bg-foreground text-xs font-semibold text-background">MR</div><div><p className="text-xs font-medium">Maya Rao</p><p className="text-[11px] text-muted">Developer experience</p></div><span className="ml-auto rounded border border-border px-2 py-1 font-mono text-[10px] text-muted">Follow</span></div></div><div className="rounded-xl border border-border bg-background p-4"><span className="font-mono text-[10px] uppercase tracking-widest text-muted">Active discussion</span><p className="mt-4 text-sm font-medium leading-5">What makes documentation actually useful?</p><div className="mt-5 flex items-center justify-between font-mono text-[10px] text-muted"><span>12 replies</span><span className="text-accent">Join thread →</span></div></div></div>
      </div>
      <div className="border-t border-border px-5 py-3 font-mono text-[10px] text-muted"><span className="text-accent">●</span> a living index of developer knowledge</div>
    </div>
  </div>
}

function SectionLabel({ children }: { children: React.ReactNode }) { return <p className="mb-5 font-mono text-[11px] uppercase tracking-[0.22em] text-accent">{children}</p> }

export default function HomePage() {
  return <main>
    <section className="relative overflow-hidden border-b border-border/70"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_75%_30%,hsl(var(--accent)/.11),transparent_30%)]" /><div className="mx-auto grid max-w-7xl items-center gap-16 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-[.9fr_1.1fr] lg:gap-12 lg:py-32"><div className="relative"><SectionLabel>A developer community for the work behind the work</SectionLabel><h1 className="max-w-2xl text-5xl font-semibold leading-[.98] tracking-[-0.055em] sm:text-7xl">Build your <span className="text-accent">thinking</span> in public.</h1><p className="mt-7 max-w-xl text-base leading-7 text-muted sm:text-lg">Commun is where developers publish what they learn, discover useful ideas, discuss technical subjects, and build a public identity around their work.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/register" className="rounded-md bg-accent px-5 py-3 text-center text-sm font-semibold text-background transition-transform hover:-translate-y-0.5">Join Commun <span aria-hidden="true">→</span></Link><Link href="/explore" className="rounded-md border border-border px-5 py-3 text-center text-sm font-semibold transition-colors hover:border-muted hover:bg-surface">Explore Commun</Link></div><div className="mt-12 flex flex-wrap gap-x-6 gap-y-2 border-t border-border/70 pt-5 font-mono text-[10px] uppercase tracking-widest text-muted"><span>Read</span><span>Write</span><span>Discuss</span><span>Connect</span></div></div><ProductPreview /></div></section>

    <section className="border-b border-border/70"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:px-8 md:grid-cols-[1fr_2fr] md:items-center"><div><SectionLabel>The network</SectionLabel><h2 className="max-w-sm text-2xl font-semibold tracking-tight sm:text-3xl">Knowledge gets better when it has somewhere to go.</h2></div><div className="grid grid-cols-2 gap-px overflow-hidden rounded-xl border border-border bg-border sm:grid-cols-4"><div className="bg-background p-5"><p className="font-mono text-2xl text-accent">↗</p><p className="mt-4 text-sm font-medium">Developers</p><p className="mt-1 text-xs text-muted">people with context</p></div><div className="bg-background p-5"><p className="font-mono text-2xl text-accent">#</p><p className="mt-4 text-sm font-medium">Topics</p><p className="mt-1 text-xs text-muted">ideas worth following</p></div><div className="bg-background p-5"><p className="font-mono text-2xl text-accent">▤</p><p className="mt-4 text-sm font-medium">Articles</p><p className="mt-1 text-xs text-muted">lessons that travel</p></div><div className="bg-background p-5"><p className="font-mono text-2xl text-accent">↔</p><p className="mt-4 text-sm font-medium">Discussions</p><p className="mt-1 text-xs text-muted">questions in motion</p></div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8 sm:py-32"><div className="max-w-xl"><SectionLabel>What you can do here</SectionLabel><h2 className="text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">A better home for technical curiosity.</h2><p className="mt-5 text-muted leading-7">Not another feed to keep up with. A place to make your work legible, useful, and connected to the people thinking about similar problems.</p></div><div className="mt-14 grid border-l border-t border-border sm:grid-cols-2 lg:grid-cols-3">{capabilities.map(([number, title, text, icon]) => <article key={number} className="group border-b border-r border-border p-6 transition-colors hover:bg-surface sm:p-8"><div className="flex items-start justify-between"><span className="font-mono text-xs text-accent">{number}</span><span className="font-mono text-xl text-muted transition-colors group-hover:text-accent" aria-hidden="true">{icon}</span></div><h3 className="mt-12 text-lg font-semibold tracking-tight">{title}</h3><p className="mt-3 text-sm leading-6 text-muted">{text}</p></article>)}</div></section>

    <section className="border-y border-border/70 bg-surface/40"><div className="mx-auto grid max-w-7xl gap-16 px-5 py-24 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center lg:py-32"><div><SectionLabel>How Commun works</SectionLabel><h2 className="text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Small steps. Real momentum.</h2><div className="mt-10 flex flex-col gap-7">{['Create your developer identity', 'Discover people and knowledge', 'Publish and participate', 'Build your network'].map((step, index) => <div className="flex gap-4" key={step}><span className="font-mono text-xs text-accent">0{index + 1}</span><p className="text-sm font-medium">{step}</p></div>)}</div></div><div className="rounded-2xl border border-border bg-background p-5 sm:p-8"><div className="flex items-center justify-between border-b border-border pb-5"><span className="font-mono text-[10px] uppercase tracking-widest text-muted">A note worth sharing</span><span className="text-xs text-muted">design example</span></div><p className="py-10 text-2xl font-medium leading-tight tracking-tight sm:text-3xl">“The best developer communities make it easier to ask a precise question — and easier to share a useful answer.”</p><div className="flex items-center justify-between border-t border-border pt-5"><span className="font-mono text-xs text-accent">#community #craft</span><span className="text-xs text-muted">Save · Discuss</span></div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-3xl text-center"><SectionLabel>Start with a question</SectionLabel><h2 className="text-4xl font-semibold tracking-[-0.05em] sm:text-6xl">Your next idea could help another developer.</h2><p className="mx-auto mt-6 max-w-xl text-muted leading-7">Join a community built around sharing the work, lessons, and questions that usually stay in the margins.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/register" className="rounded-md bg-accent px-5 py-3 text-center text-sm font-semibold text-background">Join Commun <span aria-hidden="true">→</span></Link><Link href="/community" className="rounded-md border border-border px-5 py-3 text-center text-sm font-semibold hover:bg-surface">Explore discussions</Link></div></div></section>

    <footer className="border-t border-border"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-12 sm:px-8 md:grid-cols-[1.4fr_repeat(3,1fr)]"><div><Link href="/" className="font-mono text-lg font-bold">commun<span className="text-accent">.</span></Link><p className="mt-4 max-w-xs text-sm leading-6 text-muted">A focused home for developers to read, write, and build together.</p></div><div><p className="font-mono text-[10px] uppercase tracking-widest text-muted">Product</p><div className="mt-4 flex flex-col gap-3 text-sm"><Link href="/explore" className="hover:text-accent">Discover</Link><Link href="/community" className="hover:text-accent">Discussions</Link><Link href="/explore" className="hover:text-accent">Developers</Link><Link href="/write" className="hover:text-accent">Write</Link></div></div><div><p className="font-mono text-[10px] uppercase tracking-widest text-muted">Company</p><div className="mt-4 flex flex-col gap-3 text-sm text-muted"><span>About</span><span>Contact</span></div></div><div><p className="font-mono text-[10px] uppercase tracking-widest text-muted">Resources</p><div className="mt-4 flex flex-col gap-3 text-sm text-muted"><span>Guidelines</span><span>Privacy</span><span>Terms</span></div></div></div><div className="mx-auto flex max-w-7xl justify-between border-t border-border px-5 py-5 font-mono text-[10px] text-muted sm:px-8"><span>© 2026 Commun</span><span>Built for thoughtful developers.</span></div></footer>
  </main>
}
