'use client'

import Link from 'next/link'
import { usePathname, useRouter, useSearchParams } from 'next/navigation'
import { useEffect, useState } from 'react'

type SearchType = 'all' | 'developers' | 'articles' | 'discussions' | 'topics'
type SearchData = { developers: Bucket<Developer>; articles: Bucket<Article>; discussions: Bucket<Discussion>; topics: Bucket<Topic> }
type Bucket<T> = { items: T[]; page: number; limit: number; total: number; hasNextPage: boolean }
type Developer = { id: string; display_name: string | null; username: string | null; bio: string | null; avatar_url: string | null; interests: string[] | null }
type Author = { id: string; display_name: string | null; username: string | null; avatar_url: string | null } | null
type Article = { id: string; slug: string; title: string; excerpt: string | null; reading_time_minutes: number; published_at: string | null; author: Author }
type Discussion = { id: string; title: string; content: string; created_at: string; is_closed: boolean; author: Author; topic: { id: string; name: string } | null }
type Topic = { id: string; name: string; description: string | null }

const tabs: { label: string; value: SearchType }[] = [{ label: 'All', value: 'all' }, { label: 'Developers', value: 'developers' }, { label: 'Articles', value: 'articles' }, { label: 'Discussions', value: 'discussions' }, { label: 'Topics', value: 'topics' }]
const emptyCopy: Record<SearchType, string> = { all: 'Try a broader keyword or explore what the community has already published.', developers: 'No active developer profiles matched that search.', articles: 'No published articles matched that search.', discussions: 'No open discussions matched that search.', topics: 'No topics matched that search.' }

export function SearchInterface() {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const query = params.get('q') ?? ''; const type = (params.get('type') as SearchType) || 'all'; const page = Math.max(1, Number(params.get('page')) || 1)
  const [input, setInput] = useState(query); const [data, setData] = useState<SearchData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { const controller = new AbortController(); fetch(`/api/search?${new URLSearchParams({ q: query, type, page: String(page), limit: '12' })}`, { signal: controller.signal }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result) }).catch((reason) => { if (reason.name !== 'AbortError') setError('Search is temporarily unavailable.') }).finally(() => setLoading(false)); return () => controller.abort() }, [query, type, page])
  function update(next: Partial<{ q: string; type: SearchType; page: number }>) { const nextParams = new URLSearchParams(params.toString()); if (next.q !== undefined) next.q ? nextParams.set('q', next.q) : nextParams.delete('q'); if (next.type !== undefined) next.type === 'all' ? nextParams.delete('type') : nextParams.set('type', next.type); nextParams.set('page', String(next.page ?? 1)); router.push(`${pathname}?${nextParams.toString()}`) }
  function submit(event: React.FormEvent) { event.preventDefault(); update({ q: input.trim(), page: 1 }) }
  const total = data ? data.developers.total + data.articles.total + data.discussions.total + data.topics.total : 0
  const activeBucket = type === 'developers' ? data?.developers : type === 'articles' ? data?.articles : type === 'discussions' ? data?.discussions : type === 'topics' ? data?.topics : null
  return <div className="mx-auto w-full max-w-6xl px-5 py-10 sm:px-8 lg:px-10"><header className="border-b border-border pb-8"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-accent">Search Commun</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Find useful signal.</h1><form key={`${query}-${type}-${page}`} onSubmit={submit} className="mt-6 flex max-w-2xl gap-2" role="search"><label htmlFor="global-search" className="sr-only">Search Commun</label><input id="global-search" value={input} onChange={(event) => setInput(event.target.value)} placeholder="Search developers, articles, discussions, topics" className="min-w-0 flex-1 rounded-lg border border-border bg-surface px-4 py-3 text-sm outline-none focus:border-accent" /><button className="rounded-lg bg-accent px-5 py-3 text-sm font-semibold text-background">Search</button></form></header><nav aria-label="Search filters" className="flex gap-2 overflow-x-auto border-b border-border py-4">{tabs.map((tab) => <button key={tab.value} type="button" onClick={() => update({ type: tab.value, page: 1 })} className={`shrink-0 rounded-lg px-3 py-2 text-xs font-medium ${type === tab.value ? 'bg-accent text-background' : 'text-muted hover:bg-surface hover:text-foreground'}`}>{tab.label}</button>)}</nav>{loading ? <div role="status" className="py-16 text-center text-sm text-muted">Searching real Commun content…</div> : error ? <div role="alert" className="py-16 text-center text-sm text-red-300">{error}</div> : !query ? <div className="grid gap-4 py-8 md:grid-cols-3"><SearchPrompt title="Find developers" description="Search profiles by name, username, bio, or interests." type="developers" onChoose={update} /><SearchPrompt title="Read articles" description="Look through published writing and practical notes." type="articles" onChoose={update} /><SearchPrompt title="Join discussions" description="Find open conversations and questions from the community." type="discussions" onChoose={update} /></div> : <div className="py-8"><p className="mb-6 text-sm text-muted">{total} result{total === 1 ? '' : 's'} for <span className="text-foreground">“{query}”</span></p>{type === 'all' ? <AllResults data={data!} /> : activeBucket?.items.length ? <ResultSection type={type} items={activeBucket.items} /> : <div className="rounded-xl border border-dashed border-border p-10 text-center text-sm text-muted">{emptyCopy[type]}</div>}{type !== 'all' && activeBucket && activeBucket.total > activeBucket.limit && <Pagination page={page} hasNextPage={activeBucket.hasNextPage} onChange={(nextPage) => update({ page: nextPage })} />}</div>}</div>
}

function SearchPrompt({ title, description, type, onChoose }: { title: string; description: string; type: SearchType; onChoose: (next: { type: SearchType; page: number }) => void }) { return <button type="button" onClick={() => onChoose({ type, page: 1 })} className="rounded-xl border border-border bg-surface p-5 text-left transition hover:-translate-y-0.5 hover:border-accent/50"><p className="text-sm font-semibold">{title}</p><p className="mt-2 text-sm leading-6 text-muted">{description}</p><span className="mt-5 block text-xs font-semibold text-accent">Start exploring →</span></button> }
function AllResults({ data }: { data: SearchData }) { return <div className="space-y-10"><ResultSection type="developers" items={data.developers.items.slice(0, 4)} /><ResultSection type="articles" items={data.articles.items.slice(0, 4)} /><ResultSection type="discussions" items={data.discussions.items.slice(0, 4)} /><ResultSection type="topics" items={data.topics.items.slice(0, 4)} /></div> }
function ResultSection({ type, items }: { type: SearchType; items: unknown[] }) { if (!items.length) return null; const labels: Record<string, string> = { developers: 'Developers', articles: 'Articles', discussions: 'Discussions', topics: 'Topics' }; return <section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold">{labels[type]}</h2></div><div className="grid gap-3">{items.map((item: any) => type === 'developers' ? <Link key={item.id} href={`/profile/${item.username}`} className="rounded-xl border border-border bg-surface p-4 hover:border-accent/50"><p className="font-medium">{item.display_name || item.username}</p><p className="mt-1 text-xs text-muted">@{item.username}</p><p className="mt-2 line-clamp-2 text-sm text-muted">{item.bio || (item.interests ?? []).join(' · ')}</p></Link> : type === 'articles' ? <Link key={item.id} href={`/post/${item.slug}`} className="rounded-xl border border-border bg-surface p-4 hover:border-accent/50"><p className="font-medium">{item.title}</p><p className="mt-2 line-clamp-2 text-sm text-muted">{item.excerpt || 'Published article'}</p><p className="mt-3 text-xs text-muted">{item.author?.display_name || item.author?.username || 'Commun developer'} · {item.reading_time_minutes} min read</p></Link> : type === 'discussions' ? <Link key={item.id} href={`/discussions/${item.id}`} className="rounded-xl border border-border bg-surface p-4 hover:border-accent/50"><p className="font-medium">{item.title}</p><p className="mt-2 line-clamp-2 text-sm text-muted">{item.content}</p><p className="mt-3 text-xs text-muted">{item.topic?.name || 'Discussion'} · {item.is_closed ? 'Closed' : 'Open'}</p></Link> : <Link key={item.id} href={`/explore?topic=${item.id}`} className="rounded-xl border border-border bg-surface p-4 hover:border-accent/50"><p className="font-medium">{item.name}</p><p className="mt-2 line-clamp-2 text-sm text-muted">{item.description || 'Explore articles and discussions on this topic.'}</p></Link>)}</div></section> }
function Pagination({ page, hasNextPage, onChange }: { page: number; hasNextPage: boolean; onChange: (page: number) => void }) { return <div className="mt-8 flex items-center justify-between border-t border-border pt-5"><button type="button" disabled={page === 1} onClick={() => onChange(page - 1)} className="rounded-lg border border-border px-3 py-2 text-xs text-muted disabled:opacity-40">Previous</button><span className="font-mono text-xs text-muted">Page {page}</span><button type="button" disabled={!hasNextPage} onClick={() => onChange(page + 1)} className="rounded-lg border border-border px-3 py-2 text-xs text-muted disabled:opacity-40">Next</button></div> }
