import Link from 'next/link'
import { redirect } from 'next/navigation'
import { canModerate, getAuthContext } from '@/lib/auth'
import { createAdminClient } from '@/lib/admin'
import { EmptyState } from '@/components/ui/primitives'
import { FilterBar, SectionHeader, StatusBadge, Surface } from '@/components/ui/product-surfaces'

export default async function ModerationPage({ searchParams }: { searchParams: Promise<{ status?: string; page?: string }> }) {
  const context = await getAuthContext(); if (!context) redirect('/login?next=/moderation'); if (!canModerate(context)) redirect('/feed'); const params = await searchParams; const page = Math.max(1, Number(params.page ?? 1)); const size = 20; const db = createAdminClient(); let query = db.from('reports').select('id,target_type,target_id,reason,status,reporter_id,created_at,resolution_note', { count: 'exact' }).order('created_at', { ascending: false }).range((page - 1) * size, page * size - 1); if (params.status && ['OPEN','IN_REVIEW','RESOLVED','DISMISSED'].includes(params.status)) query = query.eq('status', params.status); const { data: reports } = await query
  const filters = ['ALL','OPEN','IN_REVIEW','RESOLVED','DISMISSED']
  return <main className="mx-auto w-full max-w-6xl px-5 py-10 sm:px-8 lg:px-10"><SectionHeader eyebrow="Trust & safety" title="Moderation queue" description="Review community reports and record accountable decisions." /><FilterBar>{filters.map((status) => <Link key={status} href={status === 'ALL' ? '/moderation' : `/moderation?status=${status}`} className={`rounded-lg px-3 py-2 font-mono text-[10px] uppercase tracking-wider transition ${params.status === status || (!params.status && status === 'ALL') ? 'bg-accent text-background' : 'text-muted hover:bg-surface hover:text-foreground'}`}>{status.replace('_',' ')}</Link>)}</FilterBar><div className="mt-5">{reports?.length ? <Surface className="overflow-hidden"><div className="hidden grid-cols-[1.4fr_1fr_1fr_120px] gap-4 border-b border-border px-5 py-3 font-mono text-[10px] uppercase tracking-wider text-muted md:grid"><span>Report</span><span>Target</span><span>Created</span><span>Status</span></div>{reports.map((report) => <Link href={`/moderation/reports/${report.id}`} key={report.id} className="grid gap-3 border-b border-border p-5 transition last:border-0 hover:bg-elevated md:grid-cols-[1.4fr_1fr_1fr_120px] md:items-center md:gap-4"><div><p className="font-medium">{report.reason.replace('_',' ')}</p><p className="mt-1 font-mono text-[10px] uppercase text-muted">{report.target_type} · {report.id.slice(0,8)}</p></div><p className="font-mono text-xs text-muted">{report.target_id.slice(0,8)}…</p><p className="text-xs text-muted">{new Date(report.created_at).toLocaleDateString()}</p><StatusBadge tone={report.status === 'OPEN' ? 'accent' : 'neutral'}>{report.status.replace('_',' ')}</StatusBadge></Link>)}</Surface> : <EmptyState title="No reports in this view" description="The moderation queue is clear for the selected status." />}</div></main>
}
