import Link from 'next/link'
import { redirect } from 'next/navigation'
import { canModerate, getAuthContext } from '@/lib/auth'
import { createAdminClient } from '@/lib/admin'

export default async function ModerationPage({ searchParams }: { searchParams: Promise<{ status?: string; page?: string }> }) {
  const context = await getAuthContext(); if (!context) redirect('/login?next=/moderation'); if (!canModerate(context)) redirect('/feed')
  const params = await searchParams; const page = Math.max(1, Number(params.page ?? 1)); const size = 20; const db = createAdminClient(); let query = db.from('reports').select('id,target_type,target_id,reason,status,reporter_id,created_at,resolution_note', { count: 'exact' }).order('created_at', { ascending: false }).range((page - 1) * size, page * size - 1)
  if (params.status && ['OPEN','IN_REVIEW','RESOLVED','DISMISSED'].includes(params.status)) query = query.eq('status', params.status)
  const { data: reports, count } = await query
  return <main className="mx-auto max-w-6xl px-6 py-10"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-accent">Trust & safety</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Moderation queue</h1><p className="mt-2 text-sm text-muted-foreground">Review community reports and record accountable decisions.</p></div><div className="flex gap-2 text-xs">{['ALL','OPEN','IN_REVIEW','RESOLVED','DISMISSED'].map((status) => <Link key={status} href={status === 'ALL' ? '/moderation' : `/moderation?status=${status}`} className={`rounded-full border px-3 py-1.5 ${params.status === status || (!params.status && status === 'ALL') ? 'border-accent text-accent' : 'border-border text-muted-foreground'}`}>{status.replace('_',' ')}</Link>)}</div></div><section className="overflow-hidden rounded-xl border border-border bg-surface"><div className="grid grid-cols-[1fr_1fr_1fr_110px] gap-4 border-b border-border px-5 py-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground"><span>Report</span><span>Target</span><span>Created</span><span>Status</span></div>{reports?.length ? reports.map((report) => <Link href={`/moderation/reports/${report.id}`} key={report.id} className="grid grid-cols-[1fr_1fr_1fr_110px] gap-4 border-b border-border px-5 py-4 text-sm hover:bg-background"><div><p className="font-medium">{report.reason.replace('_',' ')}</p><p className="text-xs text-muted-foreground">{report.target_type} · {report.id.slice(0,8)}</p></div><p className="text-muted-foreground">{report.target_id.slice(0,8)}…</p><p className="text-muted-foreground">{new Date(report.created_at).toLocaleDateString()}</p><span className="text-xs font-semibold text-accent">{report.status.replace('_',' ')}</span></Link>) : <div className="px-5 py-16 text-center"><p className="font-medium">No reports in this view</p><p className="mt-2 text-sm text-muted-foreground">The queue is clear for the selected filter.</p></div>}</section><p className="mt-3 text-xs text-muted-foreground">{count ?? 0} total reports · page {page}</p></main>
}
