import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import { PageContainer, Card, EmptyState } from '@/components/ui/primitives'

export default async function ExplorePage({ searchParams }: { searchParams: Promise<{ topic?: string }> }) {
  const { topic } = await searchParams
  const supabase = await createClient()
  const [{ data: topicPostLinks }, { data: articles }, { data: discussions }, { data: topics }, { data: developers }] = await Promise.all([
    topic ? supabase.from('post_topics').select('post_id').eq('topic_id', topic) : Promise.resolve({ data: [] as { post_id: string }[] }),
    supabase.from('posts').select('id,title,slug,excerpt,reading_time_minutes,published_at,author_id').eq('status', 'PUBLISHED').order('published_at', { ascending: false }).limit(24),
    (() => { let query = supabase.from('discussions').select('id,title,content,is_closed,created_at,topic_id').eq('is_removed', false); if (topic) query = query.eq('topic_id', topic); return query.order('created_at', { ascending: false }).limit(6) })(),
    supabase.from('topics').select('id,name').order('name').limit(12),
    supabase.from('profiles').select('id,display_name,username,bio,interests').eq('status', 'ACTIVE').not('username', 'is', null).order('display_name').limit(6),
  ])
  const topicPostIds = topic ? new Set((topicPostLinks ?? []).map((link) => link.post_id)) : null
  const visibleArticles = (articles ?? []).filter((article) => !topicPostIds || topicPostIds.has(article.id)).slice(0, 6)
  const articleAuthors = [...new Set(visibleArticles.map((article) => article.author_id))]
  const { data: authors } = articleAuthors.length ? await supabase.from('profiles').select('id,display_name,username').in('id', articleAuthors) : { data: [] as { id: string; display_name: string | null; username: string | null }[] }
  const authorMap = new Map((authors ?? []).map((author) => [author.id, author]))
  const selectedTopic = topics?.find((item) => item.id === topic)
  return <PageContainer eyebrow="Find your next thread" title="Explore" description="Discover real writing, open conversations, topics, and developers across Commun.">
    <div className="flex flex-wrap gap-2"><Link href="/explore" className={`rounded-lg px-3 py-2 text-xs font-semibold ${!topic ? 'bg-accent text-background' : 'border border-border text-muted'}`}>All</Link>{(topics ?? []).map((item) => <Link key={item.id} href={`/explore?topic=${item.id}`} className={`rounded-lg px-3 py-2 text-xs ${topic === item.id ? 'bg-accent text-background' : 'border border-border text-muted hover:bg-surface'}`}>{item.name}</Link>)}</div>
    {selectedTopic && <Card className="border-accent/30"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-accent">Topic</p><h2 className="mt-2 text-xl font-semibold">{selectedTopic.name}</h2><p className="mt-2 text-sm leading-6 text-muted">Explore published articles and discussions associated with this topic.</p></Card>}
    <div className="grid gap-4 lg:grid-cols-2"><Card><div className="flex items-center justify-between"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-accent">Latest articles</p><Link href="/search?type=articles" className="text-xs text-muted hover:text-foreground">Search all →</Link></div><div className="mt-5 space-y-3">{visibleArticles.map((article) => <Link key={article.id} href={`/post/${article.slug}`} className="block rounded-lg border border-border p-4 hover:border-accent/50"><p className="font-medium">{article.title}</p><p className="mt-1 line-clamp-2 text-sm text-muted">{article.excerpt || 'Published article'}</p><p className="mt-3 text-xs text-muted">{authorMap.get(article.author_id)?.display_name || authorMap.get(article.author_id)?.username || 'Commun developer'} · {article.reading_time_minutes} min read</p></Link>)}{!articles?.length && <EmptyState title="No published articles yet." description="Be the first to write something useful for another developer." action="Write an article" href="/write" />}</div></Card><Card><div className="flex items-center justify-between"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-accent">Open discussions</p><Link href="/search?type=discussions" className="text-xs text-muted hover:text-foreground">Search all →</Link></div><div className="mt-5 space-y-3">{(discussions ?? []).map((discussion) => <Link key={discussion.id} href={`/discussions/${discussion.id}`} className="block rounded-lg border border-border p-4 hover:border-accent/50"><p className="font-medium">{discussion.title}</p><p className="mt-1 line-clamp-2 text-sm text-muted">{discussion.content}</p><p className="mt-3 text-xs text-muted">{discussion.is_closed ? 'Closed' : 'Open'} · {new Date(discussion.created_at).toLocaleDateString()}</p></Link>)}{!discussions?.length && <EmptyState title="No discussions yet." description="Start a conversation around a real question or idea." action="Start a discussion" href="/discussions/new" />}</div></Card></div>
    <div className="grid gap-4 lg:grid-cols-[1fr_1fr]"><Card><div className="flex items-center justify-between"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-accent">Topics</p><Link href="/search?type=topics" className="text-xs text-muted hover:text-foreground">Search all →</Link></div><div className="mt-5 flex flex-wrap gap-2">{(topics ?? []).map((item) => <Link key={item.id} href={`/explore?topic=${item.id}`} className="rounded-full border border-border px-3 py-2 text-xs text-muted hover:border-accent hover:text-accent">{item.name}</Link>)}{!topics?.length && <p className="text-sm text-muted">Topics will appear as developers share what they are learning.</p>}</div></Card><Card><div className="flex items-center justify-between"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-accent">Developers</p><Link href="/search?type=developers" className="text-xs text-muted hover:text-foreground">Search all →</Link></div><div className="mt-5 space-y-3">{(developers ?? []).map((developer) => <Link key={developer.id} href={`/profile/${developer.username}`} className="block rounded-lg border border-border p-4 hover:border-accent/50"><p className="font-medium">{developer.display_name || developer.username}</p><p className="mt-1 text-xs text-muted">@{developer.username}</p><p className="mt-2 line-clamp-2 text-sm text-muted">{developer.bio || (developer.interests ?? []).join(' · ')}</p></Link>)}{!developers?.length && <EmptyState title="No developers to surface yet." description="Complete an active profile to appear in discovery." action="Find developers" href="/discover" />}</div></Card></div>
  </PageContainer>
}
