'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { authMessage, emailSchema, fieldErrors, loginSchema, registerSchema, resetSchema, safeNext } from '@/lib/auth/validation'

function Field({ label, name, type = 'text', value, onChange, error, autoComplete }: { label: string; name: string; type?: string; value: string; onChange: (value: string) => void; error?: string; autoComplete?: string }) { return <label className="flex flex-col gap-2 text-sm"><span className="font-medium">{label}</span><input name={name} type={type} value={value} onChange={(event) => onChange(event.target.value)} autoComplete={autoComplete} aria-invalid={Boolean(error)} className="rounded-md border border-border bg-background px-3 py-3 text-foreground outline-none transition focus:border-accent focus:ring-2 focus:ring-accent/20" />{error && <span className="text-xs text-red-300">{error}</span>}</label> }
function PasswordField(props: Omit<React.ComponentProps<typeof Field>, 'type'>) { const [visible, setVisible] = useState(false); return <div className="relative"><Field {...props} type={visible ? 'text' : 'password'} /><button type="button" onClick={() => setVisible(!visible)} className="absolute right-3 top-9 text-xs text-muted hover:text-foreground" aria-label={visible ? 'Hide password' : 'Show password'}>{visible ? 'Hide' : 'Show'}</button></div> }
function AuthCard({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <main className="mx-auto flex min-h-[calc(100vh-73px)] max-w-6xl items-center px-5 py-12 sm:px-8"><div className="grid w-full gap-12 lg:grid-cols-[1fr_440px] lg:items-center"><section className="hidden lg:block"><p className="font-mono text-sm text-accent">COMMUN / IDENTITY</p><h1 className="mt-5 max-w-xl text-5xl font-semibold tracking-tight">A better way to build in public.</h1><p className="mt-6 max-w-lg text-lg leading-8 text-muted">Your work, your people, and your next idea in one focused network.</p></section><section className="rounded-xl border border-border bg-surface p-6 shadow-2xl shadow-black/20 sm:p-8"><p className="font-mono text-xs uppercase tracking-[0.2em] text-accent">{title}</p><p className="mt-3 text-sm leading-6 text-muted">{description}</p>{children}</section></div></main> }
function Submit({ loading, children }: { loading: boolean; children: React.ReactNode }) { return <button disabled={loading} className="w-full rounded-md bg-accent px-4 py-3 text-sm font-semibold text-background transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-60">{loading ? 'Please wait…' : children}</button> }

export function LoginForm() { const router = useRouter(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setError(''); const parsed = loginSchema.safeParse({ email, password }); if (!parsed.success) { setError(fieldErrors(parsed.error).email ?? fieldErrors(parsed.error).password); return } setLoading(true); const { error: authError } = await createClient().auth.signInWithPassword(parsed.data); if (authError) { setError(authMessage(authError.message)); setLoading(false); return } const next = safeNext(new URLSearchParams(window.location.search).get('next')); router.push(next) } return <AuthCard title="Welcome back" description="Log in to continue where you left off."><form onSubmit={submit} className="mt-8 flex flex-col gap-5"><Field label="Email" name="email" type="email" value={email} onChange={setEmail} error={error && !password ? error : undefined} autoComplete="email" /><PasswordField label="Password" name="password" value={password} onChange={setPassword} autoComplete="current-password" /><div className="flex justify-end"><Link href="/forgot-password" className="text-xs text-accent hover:underline">Forgot password?</Link></div>{error && <p role="alert" aria-live="polite" className="text-sm text-red-300">{error}</p>}<Submit loading={loading}>Log in</Submit><p className="text-center text-sm text-muted">New to Commun? <Link href="/register" className="text-accent hover:underline">Create an account</Link></p></form></AuthCard> }

export function RegisterForm() { const router = useRouter(); const [form, setForm] = useState({ name: '', username: '', email: '', password: '', confirmPassword: '' }); const [errors, setErrors] = useState<Record<string, string>>({}); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false); const set = (key: keyof typeof form) => (value: string) => setForm((current) => ({ ...current, [key]: value })); async function submit(event: FormEvent) { event.preventDefault(); setMessage(''); const parsed = registerSchema.safeParse(form); if (!parsed.success) { setErrors(fieldErrors(parsed.error)); return } setErrors({}); setLoading(true); const supabase = createClient(); const { data, error } = await supabase.auth.signUp({ email: parsed.data.email, password: parsed.data.password, options: { emailRedirectTo: process.env.NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL ?? `${window.location.origin}/auth/callback`, data: { name: parsed.data.name, username: parsed.data.username } } }); if (error) { setMessage(authMessage(error.message)); setLoading(false); return } if (data.user) { await supabase.from('profiles').upsert({ id: data.user.id, username: parsed.data.username }, { onConflict: 'id' }) } router.push(data.session ? '/onboarding' : '/verify-email') } return <AuthCard title="Join Commun" description="Create a developer identity that grows with your work."><form onSubmit={submit} className="mt-8 flex flex-col gap-4"><Field label="Name" name="name" value={form.name} onChange={set('name')} error={errors.name} autoComplete="name" /><Field label="Username" name="username" value={form.username} onChange={set('username')} error={errors.username} autoComplete="username" /><Field label="Email" name="email" type="email" value={form.email} onChange={set('email')} error={errors.email} autoComplete="email" /><PasswordField label="Password" name="password" value={form.password} onChange={set('password')} error={errors.password} autoComplete="new-password" /><PasswordField label="Confirm password" name="confirmPassword" value={form.confirmPassword} onChange={set('confirmPassword')} error={errors.confirmPassword} autoComplete="new-password" />{message && <p role="alert" aria-live="polite" className="text-sm text-red-300">{message}</p>}<Submit loading={loading}>Create account</Submit><p className="text-center text-sm text-muted">Already have an account? <Link href="/login" className="text-accent hover:underline">Log in</Link></p></form></AuthCard> }

export function ForgotPasswordForm() { const [email, setEmail] = useState(''); const [error, setError] = useState(''); const [sent, setSent] = useState(false); const [loading, setLoading] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); const parsed = emailSchema.safeParse({ email }); if (!parsed.success) { setError('Enter a valid email.'); return } setLoading(true); setError(''); await createClient().auth.resetPasswordForEmail(parsed.data.email, { redirectTo: `${window.location.origin}/reset-password` }); setSent(true); setLoading(false) } return <AuthCard title="Reset access" description="We will send a reset link if an account matches that email."><form onSubmit={submit} className="mt-8 flex flex-col gap-5"><Field label="Email" name="email" type="email" value={email} onChange={setEmail} error={error} autoComplete="email" />{sent ? <p role="status" className="text-sm text-accent">Check your inbox for a password reset link.</p> : <Submit loading={loading}>Send reset link</Submit>}<Link href="/login" className="text-center text-sm text-muted hover:text-foreground">Back to log in</Link></form></AuthCard> }

export function ResetPasswordForm() { const router = useRouter(); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); const parsed = resetSchema.safeParse({ password, confirmPassword }); if (!parsed.success) { setError(fieldErrors(parsed.error).password ?? fieldErrors(parsed.error).confirmPassword); return } setLoading(true); const { error: authError } = await createClient().auth.updateUser({ password: parsed.data.password }); if (authError) setError(authMessage(authError.message)); else router.push('/login?reset=success'); setLoading(false) } return <AuthCard title="Choose a new password" description="Use a strong password you do not reuse elsewhere."><form onSubmit={submit} className="mt-8 flex flex-col gap-5"><PasswordField label="New password" name="password" value={password} onChange={setPassword} error={error} autoComplete="new-password" /><PasswordField label="Confirm password" name="confirmPassword" value={confirmPassword} onChange={setConfirmPassword} autoComplete="new-password" />{error && <p role="alert" className="text-sm text-red-300">{error}</p>}<Submit loading={loading}>Update password</Submit></form></AuthCard> }

export function VerifyEmailContent() { return <AuthCard title="Verify your email" description="One more step before you enter Commun."><div className="mt-8 flex flex-col gap-5"><p className="text-sm leading-6 text-muted">We sent a verification link to your inbox. Open it to activate your account. If the link has expired, request a new one by registering again.</p><Link href="/login" className="rounded-md border border-border px-4 py-3 text-center text-sm font-semibold hover:bg-background">Return to log in</Link></div></AuthCard> }

export function LogoutButton() { const router = useRouter(); return <button onClick={async () => { await createClient().auth.signOut(); router.push('/') }} className="text-sm text-muted hover:text-foreground">Log out</button> }

export function AuthPages({ type }: { type: 'login' | 'register' | 'forgot' | 'reset' | 'verify' }) { return type === 'login' ? <LoginForm /> : type === 'register' ? <RegisterForm /> : type === 'forgot' ? <ForgotPasswordForm /> : type === 'reset' ? <ResetPasswordForm /> : <VerifyEmailContent /> }

