import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import { PageContainer, Card, EmptyState } from '@/components/ui/primitives'

export default async function DiscussionsPage() {
  const supabase = await createClient()
  const { data } = await supabase.from('discussions').select('id,title,content,is_pinned,is_closed,created_at').eq('is_removed', false).order('is_pinned', { ascending: false }).order('created_at', { ascending: false })
  return <PageContainer eyebrow="Ask. Share. Learn." title="Discussions" description="Questions with context, answers with care, and a community that builds in public.">
    <div className="flex flex-col gap-4 border-y border-border py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-2"><button className="rounded-lg bg-accent px-3 py-2 text-xs font-semibold text-background">Latest</button><button className="rounded-lg px-3 py-2 text-xs text-muted hover:bg-surface hover:text-foreground">Trending</button><button className="rounded-lg px-3 py-2 text-xs text-muted hover:bg-surface hover:text-foreground">Unanswered</button><button className="rounded-lg px-3 py-2 text-xs text-muted hover:bg-surface hover:text-foreground">Solved</button></div><Link href="/discussions/new" className="inline-flex w-fit rounded-lg bg-accent px-4 py-2.5 text-xs font-semibold text-background">Start a discussion <span className="ml-2">↗</span></Link></div>
    <div className="grid gap-8 xl:grid-cols-[minmax(0,1fr)_280px]"><section className="space-y-3">{(data ?? []).map((discussion) => <Link key={discussion.id} href={`/discussions/${discussion.id}`} className="group block rounded-xl border border-border bg-surface p-5 transition hover:-translate-y-0.5 hover:border-accent/50 hover:bg-elevated"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="mb-3 flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-accent"><span>Community</span><span className="text-muted">·</span><span>{discussion.is_closed ? 'Closed' : 'Open'}</span></div><h2 className="text-lg font-semibold tracking-tight group-hover:text-accent">{discussion.title}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted">{discussion.content}</p></div><span className="shrink-0 rounded-md border border-border px-2 py-1 font-mono text-[10px] text-muted">{discussion.is_closed ? 'Closed' : 'Open'}</span></div><div className="mt-5 flex items-center justify-between border-t border-border pt-4 font-mono text-[10px] text-muted"><span>{new Date(discussion.created_at).toLocaleDateString()}</span><span className="text-accent transition-transform group-hover:translate-x-1">Open thread →</span></div></Link>)}{!data?.length && <EmptyState title="No discussions yet." description="Start the first conversation and make it easier for someone else to solve a real problem." action="Start a discussion" href="/discussions/new" />}</section><aside className="hidden space-y-4 xl:block"><Card className="p-5"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-accent">Community guide</p><ul className="mt-4 space-y-3 text-xs leading-5 text-muted"><li><span className="mr-2 text-foreground">01</span> Ask a specific question.</li><li><span className="mr-2 text-foreground">02</span> Share what you tried.</li><li><span className="mr-2 text-foreground">03</span> Leave the next person with context.</li></ul></Card><Card className="p-5"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-muted">Good threads have</p><p className="mt-3 text-sm font-semibold">A clear problem, useful constraints, and an answer someone can build on.</p></Card></aside></div>
  </PageContainer>
}
