'use client'

import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'

export default function NewDiscussionPage() { const router = useRouter(); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); if (event.nativeEvent instanceof SubmitEvent && (event.nativeEvent as SubmitEvent).submitter) {} setSaving(true); setError(''); const response = await fetch('/api/discussions', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ title, content }) }); const data = await response.json(); if (!response.ok) { setError(data.error ?? 'Unable to create discussion.'); setSaving(false); return } router.push(`/discussions/${data.discussion.id}`) }
  return <main className="mx-auto max-w-3xl px-6 py-12"><p className="mb-2 text-sm font-medium uppercase tracking-[0.2em] text-orange-400">Community</p><h1 className="text-4xl font-semibold tracking-tight">Start a discussion</h1><form onSubmit={submit} className="mt-8 space-y-5"><label className="block"><span className="mb-2 block text-sm text-slate-300">Title</span><input required minLength={3} maxLength={180} value={title} onChange={(event) => setTitle(event.target.value)} className="w-full rounded-lg border border-white/10 bg-white/[.04] px-4 py-3 outline-none focus:border-orange-400" placeholder="What would you like to discuss?" /></label><label className="block"><span className="mb-2 block text-sm text-slate-300">Details</span><textarea required maxLength={10000} value={content} onChange={(event) => setContent(event.target.value)} className="min-h-52 w-full rounded-lg border border-white/10 bg-white/[.04] px-4 py-3 outline-none focus:border-orange-400" placeholder="Share context, examples, or your question..." /></label>{error && <p role="alert" className="text-sm text-red-400">{error}</p>}<button disabled={saving} className="rounded-lg bg-orange-500 px-5 py-3 font-semibold text-white disabled:opacity-50">{saving ? 'Publishing…' : 'Publish discussion'}</button></form></main>
}
