import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { canModerate, getAuthContext } from '@/lib/auth'
import { createAdminClient } from '@/lib/admin'
import { ReportActions } from '@/components/moderation/report-actions'

export default async function ReportDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const context = await getAuthContext(); if (!context) redirect('/login?next=/moderation'); if (!canModerate(context)) redirect('/feed'); const { id } = await params; const { data: report } = await createAdminClient().from('reports').select('*').eq('id', id).maybeSingle(); if (!report) notFound()
  return <main className="mx-auto max-w-4xl px-6 py-10"><Link href="/moderation" className="text-sm text-muted-foreground hover:text-foreground">← Back to queue</Link><div className="mt-6 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-accent">Report detail</p><h1 className="mt-2 text-3xl font-semibold">{report.reason.replace('_',' ')}</h1><p className="mt-2 text-sm text-muted-foreground">{report.target_type} · submitted {new Date(report.created_at).toLocaleString()}</p></div><span className="rounded-full border border-accent/40 px-3 py-1 text-xs font-semibold text-accent">{report.status}</span></div><div className="mt-8 grid gap-5 md:grid-cols-2"><section className="rounded-xl border border-border bg-surface p-5"><h2 className="font-semibold">Report context</h2><p className="mt-4 text-sm text-muted-foreground">{report.description || 'No additional description provided.'}</p><dl className="mt-5 space-y-2 text-xs"><div className="flex justify-between gap-4"><dt className="text-muted-foreground">Target ID</dt><dd className="font-mono">{report.target_id}</dd></div><div className="flex justify-between gap-4"><dt className="text-muted-foreground">Reporter</dt><dd className="font-mono">{report.reporter_id}</dd></div></dl></section><section className="rounded-xl border border-border bg-surface p-5"><h2 className="font-semibold">Actions</h2><ReportActions reportId={report.id} status={report.status} /></section></div>{report.resolution_note && <section className="mt-5 rounded-xl border border-border bg-surface p-5"><h2 className="font-semibold">Resolution note</h2><p className="mt-2 text-sm text-muted-foreground">{report.resolution_note}</p></section>}</main>
}
